
spring:
  application:
    name: product
  rabbitmq:
    host: 114.116.74.10
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf8
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://114.116.74.10:8761/eureka
user:
  username: "username"
  age: 18
